// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesDatePredictionApp.Server.Data;

#nullable disable

namespace SalesDatePredictionApp.Server.Migrations
{
    [DbContext(typeof(StoreSampleContext))]
    partial class StoreSampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Category", b =>
                {
                    b.Property<int>("Categoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Categoryid"));

                    b.Property<string>("Categoryname")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("categoryname");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.HasKey("Categoryid");

                    b.HasIndex(new[] { "Categoryname" }, "categoryname");

                    b.ToTable("Categories", "Production");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.CustOrder", b =>
                {
                    b.Property<int?>("Custid")
                        .HasColumnType("int")
                        .HasColumnName("custid");

                    b.Property<DateTime?>("Ordermonth")
                        .HasColumnType("datetime")
                        .HasColumnName("ordermonth");

                    b.Property<int?>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.ToTable((string)null);

                    b.ToView("CustOrders", "Sales");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Customer", b =>
                {
                    b.Property<int>("Custid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("custid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Custid"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("city");

                    b.Property<string>("Companyname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("companyname");

                    b.Property<string>("Contactname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("contactname");

                    b.Property<string>("Contacttitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("contacttitle");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("country");

                    b.Property<string>("Fax")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("fax");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("phone");

                    b.Property<string>("Postalcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("postalcode");

                    b.Property<string>("Region")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("region");

                    b.HasKey("Custid");

                    b.HasIndex(new[] { "City" }, "idx_nc_city");

                    b.HasIndex(new[] { "Companyname" }, "idx_nc_companyname");

                    b.HasIndex(new[] { "Postalcode" }, "idx_nc_postalcode");

                    b.HasIndex(new[] { "Region" }, "idx_nc_region");

                    b.ToTable("Customers", "Sales");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Employee", b =>
                {
                    b.Property<int>("Empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("empid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Empid"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("address");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime")
                        .HasColumnName("birthdate");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("country");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("firstname");

                    b.Property<DateTime>("Hiredate")
                        .HasColumnType("datetime")
                        .HasColumnName("hiredate");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("lastname");

                    b.Property<int?>("Mgrid")
                        .HasColumnType("int")
                        .HasColumnName("mgrid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("phone");

                    b.Property<string>("Postalcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("postalcode");

                    b.Property<string>("Region")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("region");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("title");

                    b.Property<string>("Titleofcourtesy")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("titleofcourtesy");

                    b.HasKey("Empid");

                    b.HasIndex("Mgrid");

                    b.HasIndex(new[] { "Lastname" }, "idx_nc_lastname");

                    b.HasIndex(new[] { "Postalcode" }, "idx_nc_postalcode");

                    b.ToTable("Employees", "HR");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Order", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Orderid"));

                    b.Property<int?>("Custid")
                        .HasColumnType("int")
                        .HasColumnName("custid");

                    b.Property<int>("Empid")
                        .HasColumnType("int")
                        .HasColumnName("empid");

                    b.Property<decimal>("Freight")
                        .HasColumnType("money")
                        .HasColumnName("freight");

                    b.Property<DateTime>("Orderdate")
                        .HasColumnType("datetime")
                        .HasColumnName("orderdate");

                    b.Property<DateTime>("Requireddate")
                        .HasColumnType("datetime")
                        .HasColumnName("requireddate");

                    b.Property<string>("Shipaddress")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("shipaddress");

                    b.Property<string>("Shipcity")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("shipcity");

                    b.Property<string>("Shipcountry")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("shipcountry");

                    b.Property<string>("Shipname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("shipname");

                    b.Property<DateTime?>("Shippeddate")
                        .HasColumnType("datetime")
                        .HasColumnName("shippeddate");

                    b.Property<int>("Shipperid")
                        .HasColumnType("int")
                        .HasColumnName("shipperid");

                    b.Property<string>("Shippostalcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("shippostalcode");

                    b.Property<string>("Shipregion")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("shipregion");

                    b.HasKey("Orderid");

                    b.HasIndex(new[] { "Custid" }, "idx_nc_custid");

                    b.HasIndex(new[] { "Empid" }, "idx_nc_empid");

                    b.HasIndex(new[] { "Orderdate" }, "idx_nc_orderdate");

                    b.HasIndex(new[] { "Shippeddate" }, "idx_nc_shippeddate");

                    b.HasIndex(new[] { "Shipperid" }, "idx_nc_shipperid");

                    b.HasIndex(new[] { "Shippostalcode" }, "idx_nc_shippostalcode");

                    b.ToTable("Orders", "Sales");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.OrderDetail", b =>
                {
                    b.Property<int>("Orderid")
                        .HasColumnType("int")
                        .HasColumnName("orderid");

                    b.Property<int>("Productid")
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric(4, 3)")
                        .HasColumnName("discount");

                    b.Property<short>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("qty");

                    b.Property<decimal>("Unitprice")
                        .HasColumnType("money")
                        .HasColumnName("unitprice");

                    b.HasKey("Orderid", "Productid");

                    b.HasIndex(new[] { "Orderid" }, "idx_nc_orderid");

                    b.HasIndex(new[] { "Productid" }, "idx_nc_productid");

                    b.ToTable("OrderDetails", "Sales");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.OrderPrediction", b =>
                {
                    b.Property<int>("OrderPredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderPredictionId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextPredictedOrder")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderPredictionId");

                    b.ToTable("OrderPredictions");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.OrderTotalsByYear", b =>
                {
                    b.Property<int?>("Orderyear")
                        .HasColumnType("int")
                        .HasColumnName("orderyear");

                    b.Property<int?>("Qty")
                        .HasColumnType("int")
                        .HasColumnName("qty");

                    b.ToTable((string)null);

                    b.ToView("OrderTotalsByYear", "Sales");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.OrderValue", b =>
                {
                    b.Property<int?>("Custid")
                        .HasColumnType("int")
                        .HasColumnName("custid");

                    b.Property<int>("Empid")
                        .HasColumnType("int")
                        .HasColumnName("empid");

                    b.Property<DateTime>("Orderdate")
                        .HasColumnType("datetime")
                        .HasColumnName("orderdate");

                    b.Property<int>("Orderid")
                        .HasColumnType("int")
                        .HasColumnName("orderid");

                    b.Property<int>("Shipperid")
                        .HasColumnType("int")
                        .HasColumnName("shipperid");

                    b.Property<decimal?>("Val")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("val");

                    b.ToTable((string)null);

                    b.ToView("OrderValues", "Sales");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Product", b =>
                {
                    b.Property<int>("Productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Productid"));

                    b.Property<int>("Categoryid")
                        .HasColumnType("int")
                        .HasColumnName("categoryid");

                    b.Property<bool>("Discontinued")
                        .HasColumnType("bit")
                        .HasColumnName("discontinued");

                    b.Property<string>("Productname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("productname");

                    b.Property<int>("Supplierid")
                        .HasColumnType("int")
                        .HasColumnName("supplierid");

                    b.Property<decimal>("Unitprice")
                        .HasColumnType("money")
                        .HasColumnName("unitprice");

                    b.HasKey("Productid");

                    b.HasIndex(new[] { "Categoryid" }, "idx_nc_categoryid");

                    b.HasIndex(new[] { "Productname" }, "idx_nc_productname");

                    b.HasIndex(new[] { "Supplierid" }, "idx_nc_supplierid");

                    b.ToTable("Products", "Production");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Shipper", b =>
                {
                    b.Property<int>("Shipperid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipperid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Shipperid"));

                    b.Property<string>("Companyname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("companyname");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("phone");

                    b.HasKey("Shipperid");

                    b.ToTable("Shippers", "Sales");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Supplier", b =>
                {
                    b.Property<int>("Supplierid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplierid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Supplierid"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("city");

                    b.Property<string>("Companyname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("companyname");

                    b.Property<string>("Contactname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("contactname");

                    b.Property<string>("Contacttitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("contacttitle");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("country");

                    b.Property<string>("Fax")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("fax");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("phone");

                    b.Property<string>("Postalcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("postalcode");

                    b.Property<string>("Region")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("region");

                    b.HasKey("Supplierid");

                    b.HasIndex(new[] { "Companyname" }, "idx_nc_companyname");

                    b.HasIndex(new[] { "Postalcode" }, "idx_nc_postalcode");

                    b.ToTable("Suppliers", "Production");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Employee", b =>
                {
                    b.HasOne("SalesDatePredictionApp.Server.Models.Employee", "Mgr")
                        .WithMany("InverseMgr")
                        .HasForeignKey("Mgrid")
                        .HasConstraintName("FK_Employees_Employees");

                    b.Navigation("Mgr");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Order", b =>
                {
                    b.HasOne("SalesDatePredictionApp.Server.Models.Customer", "Cust")
                        .WithMany("Orders")
                        .HasForeignKey("Custid")
                        .HasConstraintName("FK_Orders_Customers");

                    b.HasOne("SalesDatePredictionApp.Server.Models.Employee", "Emp")
                        .WithMany("Orders")
                        .HasForeignKey("Empid")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Employees");

                    b.HasOne("SalesDatePredictionApp.Server.Models.Shipper", "Shipper")
                        .WithMany("Orders")
                        .HasForeignKey("Shipperid")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Shippers");

                    b.Navigation("Cust");

                    b.Navigation("Emp");

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.OrderDetail", b =>
                {
                    b.HasOne("SalesDatePredictionApp.Server.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Orderid")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Orders");

                    b.HasOne("SalesDatePredictionApp.Server.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Productid")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Products");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Product", b =>
                {
                    b.HasOne("SalesDatePredictionApp.Server.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Categoryid")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Categories");

                    b.HasOne("SalesDatePredictionApp.Server.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("Supplierid")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Suppliers");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Employee", b =>
                {
                    b.Navigation("InverseMgr");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Shipper", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SalesDatePredictionApp.Server.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
